### ISSUE TITLE
Package architecture

### ISSUE THREAD

**Issue by KenxinKun** [fspcons/ports-service#2]
I seem to have located the `core` structures in your package, but I can't seem to find the core service interfaces. Would you be able to comment how the submission matches/differs a hexagonal architecture pattern?

**Comment by fspcons** [comment]
As I discussed with Fabrizio on the last call, I currently work with [Clean Architecture](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html) and I never had past work experience with hexagonal except reading some articles.
However, they are very similar and if I'm not mistaken Alistair developed hexagonal arch partially inspired by the clean arch and evolved it.

What acts as an Application Service on my project is the **usecases** folder. The idea is that the **app/api/handlers** folder works as a Driving Adapter (or simplified Web Controller for the clean arch). It is plugged into the usecase interactor interface that acts as a Port, except the implementation is there on the same package. The Driven Adapters are, for this project, contained in the **gateway** folder (given that there are no other external data exchange layers).

**Comment by KenxinKun** [comment]
Thanks for the clarification :)
