### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by KenxinKun** [fspcons/ports-service#3]
Hi, in reviewing the PR I noticed that there's virtually no testing across the packages. It would be great to see at least one example of unit test in the core logic (with any mock dependencies) or an integration test covering the transport/core/persistency layer, just to show in tests that it is indeed possible to create a new port and store into your in-memory database.

**Comment by fspcons** [comment]
Hello!
I'll work on it as soon as I'm able and I'll push a few commits to address that. 
However, as I saw on the instructions file:
...
> The evaluation result of the test is not linked to how much time you spend on it.
> Please DO NOT spend more than 2 hours doing it, if you haven't complete the task simply submit as is.
> Successful applications show us that 2 hours are more than enough to cover all the evaluation points below. 
...

In the interest of time, I was not able to write a lot of code and I instead left a few comments regarding how I would approach the tests. Regardless I can write a couple of tests for the handlers/usecase/gateway layers. I'll comment again once I push those.

**Comment by fspcons** [comment]
@KenxinKun I just posted a PR based on the previous fixes branch adding the requested tests and a few changes to accommodate the tests (that I didn't think about when I was trying to comply with the required 2 hours window the instructions gave me).

**Comment by KenxinKun** [comment]
Thanks for the stretch effort! I've approved the related PR (left feedback there already)
