### ISSUE TITLE
JSON loader bug

### ISSUE THREAD

**Issue by KenxinKun** [fspcons/ports-service#5]
In reviewing the PR, after I started the system with the JSON data, I started to see errors such as `failed to read a file chunk into the buffer` which seem to come from the JSON loader. This looks like a bug and the loader isn't working (just logging the error without crashing the system).

How would you fix this bug?

**Comment by fspcons** [comment]
That was a path mistake. Again, due to the short time for the test, I had to deliver as is. But here's the [PR that would fix that](https://github.com/fspcons/ports-service/pull/9)

**Comment by KenxinKun** [comment]
Fix looks good and works locally for me :)
