### ISSUE TITLE
OpenAPI spec

### ISSUE THREAD

**Issue by KenxinKun** [fspcons/ports-service#6]
I was happy to see the use of the standard OpenAPI specification in this submission. However, I was wondering why you chose version 2 instead of 3 which has been out for a while?

**Comment by fspcons** [comment]
@KenxinKun 
No particular reason. I've added the Open API spec using the [swaggo](https://github.com/swaggo/swag) coupled with [echo-swagger](https://github.com/swaggo/echo-swagger) tools (which generates the yaml/json files by scanning the code's comments). 
It looks like those libs are generating with version 2 however, [there is an issue on the repo to tackle the upgrade for version 3](https://github.com/swaggo/swag/issues/386). With more time I'd write the spec manually, but I opted to use the aforementioned tools to save time.

**Comment by KenxinKun** [comment]
Thanks for the answer!
